## Next step - use image

# version: '3'
# services:
#   prefect-server:
#     # image: prefecthq/prefect:2-python3.10
#     image: <my-image>
#     # command: prefect server start
#     ports:
#       - "4200:4200"
#     volumes:
#       - prefect:/root/.prefect
#       - /var/run/docker.sock:/var/run/docker.sock
#     environment:
#       - PREFECT_UI_URL=http://127.0.0.1:4200/api
#       - PREFECT_API_URL=http://127.0.0.1:4200/api
#       - PREFECT_SERVER_API_HOST=0.0.0.0
#       - PREFECT_API_KEY=${PREFECT_API_KEY}
# volumes:
#   prefect:


## Use docker to deploy:

    # healthcheck:
    #   test: prefect --version || exit 1
    #   interval: 10s
    #   timeout: 20s
    #   retries: 5
    #   start_period: 10s

  # prefect-setup:
  #   container_name: prefect-setup
  #   image: prefecthq/prefect:2-python3.10
  #   entrypoint: >
  #     /bin/sh -c "
  #     until curl -sSf http://prefect-server:4200/api/health; do
  #       echo 'Waiting for Prefect server...';
  #       sleep 5;
  #     done;
  #     prefect work-pool create --type docker d-p || echo 'Work pool already exists';
  #     "
  #   depends_on:
  #     prefect-server:
  #       condition: service_healthy
  #   volumes:
  #     - prefect:/root/.prefect



## Build in place:

version: '3'
services:
  prefect-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4200"
    volumes:
      - prefect:/root/.prefect
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PREFECT_UI_URL=http://prefect-server:4200/api
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_KEY=${PREFECT_API_KEY}
      - PREFECT_DOCKER_WORKPOOL=${PREFECT_DOCKER_WORKPOOL}
volumes:
  prefect: