version: '3'
services:
  prefect-server:
    image: ghcr.io/olegpodlipalin/server_image:latest
    ports:
      - "80:4200"
    volumes:
      - prefect:/root/.prefect
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PREFECT_UI_URL=http://prefect-server:4200/api
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_KEY=${PREFECT_API_KEY}
      - PREFECT_DOCKER_WORKPOOL=${PREFECT_DOCKER_WORKPOOL}
    networks:
      - worker-pool

volumes:
  prefect:
networks:
  worker-pool: