name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-16-16-115-248.eu-north-1.compute.amazonaws.com << 'EOF'
          export GITHUB_TOKEN=${GITHUB_TOKEN}
          if [ ! -d "/home/ubuntu/prefect-server" ]; then
            git clone https://github.com/OlegPodlipalin/prefect-server.git /home/ubuntu/prefect-server
          else
            cd /home/ubuntu/prefect-server
            git pull
          fi
          cd /home/ubuntu/prefect-server
          docker-compose down
          docker-compose up -d
          prefect work-pool create --type docker docker-pool
          prefect worker start --pool docker-pool
          EOF